FROM ubuntu:24.04

USER root

WORKDIR /app

RUN apt update && \
    apt install -y \
        python3-pip \
        python3-dev \
        python3.12-venv \
        libpq-dev \
        build-essential \
        pkg-config \
        supervisor \
        dos2unix \
        nginx && \
    rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt /app
RUN pip3 install --no-cache-dir --break-system-packages -r requirements.txt

COPY backend/ /app

EXPOSE 8000

COPY backend/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY backend/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["bash", "/app/entrypoint.sh"]
